name: Trigger auto deployment for demo-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-container-app-AutoDeployTrigger-c220a65e-0f78-4ddc-aa6a-d3c4538c7610.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEMOCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: swoaidemoregistry.azurecr.io
          registryUsername: ${{ secrets.DEMOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: demo-container-app
          resourceGroup: container-app-rg
          imageToBuild: swoaidemoregistry.azurecr.io/demo-container-app:${{ github.sha }}
          dockerfilePath: Dockerfile


